#!/usr/bin/env python3
"""Spanish dictionary -> build/5g-data-es.js

Reads the translation workflow's journal, applies the verifier's safety corrections
over the first pass, and writes a plain English->Spanish map. Anything absent from
the map simply renders in English, so a gap is never a breakage.
"""
import json, pathlib, re, sys, unicodedata

JOURNAL = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(
    "/Users/evanaasen/.claude/projects/-Users-evanaasen-Desktop-Claude-Cowork/"
    "9793b677-1c60-48b5-ab52-a376d8af98f7/subagents/workflows/wf_ed51bc54-2cf/journal.jsonl")
OUT = pathlib.Path("build/5g-data-es.js")

pairs, fixes = {}, {}
for line in JOURNAL.read_text().splitlines():
    try:
        e = json.loads(line)
    except Exception:
        continue
    v = e.get("result")
    if not isinstance(v, dict):
        continue
    for p in v.get("pairs", []):
        en, es = p.get("en"), p.get("es")
        if en and es:
            pairs[en] = es
    for p in v.get("problems", []):
        if p.get("en") and p.get("fixed_es"):
            fixes[p["en"]] = p["fixed_es"]

pairs.update(fixes)

def strip_ident(s: str) -> str:
    """'gluten (gluten)' -> 'gluten'. The English gloss earns its place only when the
       two words actually differ; otherwise it is noise in a narrow phone cell."""
    def same(a, b):
        n = lambda x: "".join(c for c in unicodedata.normalize("NFD", x.lower())
                              if unicodedata.category(c) != "Mn")
        return n(a) == n(b)
    return re.sub(r'\b(\w[\w\s]*?)\s*\((\w[\w\s]*?)\)',
                  lambda m: m.group(1) if same(m.group(1), m.group(2)) else m.group(0), s)

cleaned, dropped, glossed = {}, 0, 0
for en, es in pairs.items():
    es2 = strip_ident(es)
    if es2 != es:
        glossed += 1
    if es2.strip() == en.strip():      # translator left it as-is (a proper noun)
        dropped += 1
        continue
    cleaned[en] = es2

OUT.write_text("/* ============ SPANISH — generated by mkes.py. Do not hand-edit. ============\n"
               "   English -> Spanish for every visible string. A string missing from this map\n"
               "   simply renders in English, so a gap can never break a screen. ============ */\n"
               "const ES=" + json.dumps(cleaned, ensure_ascii=False, sort_keys=True) + ";\n")

print(f"  {len(pairs):,} translated  ·  {dropped:,} left as-is (proper nouns, not stored)")
print(f"  {glossed:,} redundant '(x)' glosses stripped")
print(f"  -> {OUT}  ({OUT.stat().st_size // 1024} KB, {len(cleaned):,} entries)")
