#!/usr/bin/env python3
"""Spanish dictionary -> build/5g-data-es.js

Reads the translation workflow's journal, applies the verifier's safety corrections
over the first pass, and writes a plain English->Spanish map. Anything absent from
the map simply renders in English, so a gap is never a breakage.
"""
import json, pathlib, re, sys, unicodedata

JOURNAL = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(
    "/Users/evanaasen/.claude/projects/-Users-evanaasen-Desktop-Claude-Cowork/"
    "9793b677-1c60-48b5-ab52-a376d8af98f7/subagents/workflows/wf_ed51bc54-2cf/journal.jsonl")
OUT = pathlib.Path("build/5g-data-es.js")

pairs, fixes = {}, {}
for line in JOURNAL.read_text().splitlines():
    try:
        e = json.loads(line)
    except Exception:
        continue
    v = e.get("result")
    if not isinstance(v, dict):
        continue
    for p in v.get("pairs", []):
        en, es = p.get("en"), p.get("es")
        if en and es:
            pairs[en] = es
    for p in v.get("problems", []):
        if p.get("en") and p.get("fixed_es"):
            fixes[p["en"]] = p["fixed_es"]

pairs.update(fixes)

# Strings added to the app after the translation run. The journal cannot know about
# these, so they live here and are applied last — that keeps 5g-data-es.js genuinely
# generated instead of something you have to remember not to overwrite.
LATER = {
    "Floor plan": "Plano del piso",
    "Tap a table — seats, section, where seat 1 is":
        "Toca una mesa — asientos, sección y dónde va el asiento 1",
    "Ask anything — try 'whats in the carajillo' or 'gf desserts'":
        "Pregunta lo que sea — prueba 'qué lleva el carajillo' o 'postres sin gluten'",
    "Employee Handbook": "Manual del empleado",
    "staff only": "solo personal",
    "Lock it again": "Bloquear de nuevo",
    "Floor plan": "Plano del piso",
    "Tonight's book": "La reserva de esta noche",
    "what you have plotted": "lo que has marcado",
    "Who has which section": "Quién tiene cada sección",
    "retype tonight's names — the plan recolours to match":
        "reescribe los nombres de esta noche — el plano se recolorea solo",
    "Party of": "Grupo de", "Time": "Hora", "Name": "Nombre", "optional": "opcional",
    "Seat this table": "Sentar esta mesa", "Update this table": "Actualizar esta mesa",
    "Clear it": "Borrarla", "Clear the whole book": "Borrar toda la reserva",
    "Show": "Ver", "Suggest names from": "Sugerir nombres de",
    "Put the posted names back": "Restaurar los nombres publicados",
    "Pushed together": "Mesas unidas",
    "Nothing plotted yet. Tap a table above, put in the party and the time, and it lands here.":
        "Nada marcado todavía. Toca una mesa arriba, pon el grupo y la hora, y aparece aquí.",
    "Tap any table to seat it, see who has it, and find seat 1.":
        "Toca cualquier mesa para sentarla, ver quién la tiene y encontrar el asiento 1.",
    "The printed floor plans": "Los planos impresos",
    "photographed off the wall — the live, tappable plan lives on the Money tab":
        "fotografiados de la pared — el plano interactivo está en la pestaña Dinero",
    "Seat 1 usually faces the front door. Number clockwise from there unless it is a booth. Tap a table to plot a party on it.":
        "El asiento 1 suele dar a la puerta principal. Numera en sentido horario desde ahí, salvo en los booths. Toca una mesa para marcar un grupo.",
    "Hide sections": "Ocultar secciones",
    "Show tonight's sections": "Ver las secciones de esta noche",
}
pairs.update(LATER)

def strip_ident(s: str) -> str:
    """'gluten (gluten)' -> 'gluten'. The English gloss earns its place only when the
       two words actually differ; otherwise it is noise in a narrow phone cell."""
    def same(a, b):
        n = lambda x: "".join(c for c in unicodedata.normalize("NFD", x.lower())
                              if unicodedata.category(c) != "Mn")
        return n(a) == n(b)
    return re.sub(r'\b(\w[\w\s]*?)\s*\((\w[\w\s]*?)\)',
                  lambda m: m.group(1) if same(m.group(1), m.group(2)) else m.group(0), s)

cleaned, dropped, glossed = {}, 0, 0
for en, es in pairs.items():
    es2 = strip_ident(es)
    if es2 != es:
        glossed += 1
    if es2.strip() == en.strip():      # translator left it as-is (a proper noun)
        dropped += 1
        continue
    cleaned[en] = es2

OUT.write_text("/* ============ SPANISH — generated by mkes.py. Do not hand-edit. ============\n"
               "   English -> Spanish for every visible string. A string missing from this map\n"
               "   simply renders in English, so a gap can never break a screen. ============ */\n"
               "const ES=" + json.dumps(cleaned, ensure_ascii=False, sort_keys=True) + ";\n")

print(f"  {len(pairs):,} translated  ·  {dropped:,} left as-is (proper nouns, not stored)")
print(f"  {glossed:,} redundant '(x)' glosses stripped")
print(f"  -> {OUT}  ({OUT.stat().st_size // 1024} KB, {len(cleaned):,} entries)")
