#!/usr/bin/env python3
"""Floor plans -> build/5f-data-floor.js

The four room photos become inline data: URIs (grayscale line art compresses hard),
and the table numbers become searchable text so a server can type "table 74" and
find which room it is in. Rerun after replacing a photo.
"""
import pathlib, base64, io
from PIL import Image, ImageOps

SRC = pathlib.Path("/private/tmp/claude-501/-Users-evanaasen-Desktop-Claude-Cowork/9793b677-1c60-48b5-ab52-a376d8af98f7/scratchpad/floor")
ROOMS = [
    ("Main", "IMG_5977", "the dining room you are on most nights",
     [("Booths along the back wall", ["41","42","43"]),
      ("Four-tops, middle row",      ["31","32"]),
      ("Four-tops, front row",       ["21","22","23","24"]),
      ("Booths along the front",     ["11","12","13","14"])]),
    ("Curry", "IMG_5976", "semi-private — 72 seated, 125 cocktail-style",
     [("Curved booths at the top",   ["65","84"]),
      ("Booths down the left wall",  ["51","52","53"]),
      ("Four-tops, left column",     ["62","63","64"]),
      ("Four-tops, right column",    ["72","73","74"]),
      ("Two-tops on the right",      ["82","83"]),
      ("Along the bottom",           ["61","71","81"])]),
    ("Smockton", "IMG_5975", "the big private room — 70 seated, 125 cocktail-style",
     [("The banquette",              ["91"]),
      ("Four-tops, back row",        ["96","97","98","99"]),
      ("Four-tops, front row",       ["92","93","94","95"])]),
    ("Bar", "IMG_5978", "the lounge — 25 seated",
     [("Four-tops, back row",        ["401","402","403","404"]),
      ("Four-tops, middle",          ["301","302"]),
      ("Bar seats, left to right",   ["B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11"]),
      ("Bar seats, around the end",  ["B12","B13","B14"]),
      ("High-tops",                  ["201","202","203"]),
      ("Booths along the bottom",    ["101","102","103"])]),
]

def uri(stem):
    im = ImageOps.exif_transpose(Image.open(SRC / f"{stem}.jpg")).convert("L")
    im = ImageOps.autocontrast(im, cutoff=2)
    im.thumbnail((1000, 1000), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, "JPEG", quality=72, optimize=True, progressive=True)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

out = ["/* ============ FLOOR PLANS — generated by mkfloor.py. Do not hand-edit. ============ */",
       "const FLOOR=["]
total = 0
for name, stem, sub, groups in ROOMS:
    u = uri(stem); total += len(u)
    tables = [t for _, ts in groups for t in ts]
    # tuples repr as (...) which JS reads as the comma operator — emit real arrays
    g2 = [[label, list(ts)] for label, ts in groups]
    out.append(" {n:%r,sub:%r,tables:%r,groups:%r,img:%r}," % (name, sub, tables, g2, u))
    print(f"  {name:<10}{len(tables):>3} tables  ·  {len(u)//1024} KB")
out[-1] = out[-1].rstrip(",")
out.append("];")
pathlib.Path("build/5f-data-floor.js").write_text("\n".join(out).replace("'", '"'))
print(f"  -> build/5f-data-floor.js  ({total//1024} KB of plans)")
