#!/usr/bin/env python3
"""Builds build/5d-data-photos.js from the staged dish photos.

Source is the square 260px thumbs from the photo folder. They get re-encoded down to
PX square so the whole set can live inside the one self-contained HTML file — the app
has no second file to load from. Displayed ~68px in the menu list, up to ~260px when
tapped, so PX is the quality ceiling for both.

Run: python3 mkphotos.py  ->  python3 build.py
Adding a photo: drop the square jpg in SRC named to match, add the DISHES line, rerun.
"""
import io, os, json, base64, pathlib
from PIL import Image

PX, Q = 200, 70
SRC = "/mnt/user-data/uploads/Mos-Dish-Photos/Web ready/thumbs"
ROOT = pathlib.Path(__file__).parent

# photo file (no .jpg)  ->  the EXACT menu item name in 4-data-food.js
DISHES = {
 "baked-french-onion":"Baked French Onion",
 "baked-potato":"Baked Potato",
 "blackened-creole-salmon":"Blackened Creole Salmon",
 "brown-butter-cake":"Brown Butter Cake",
 "brussels-sprouts":"Brussels Sprouts",
 "calamari":"Calamari",
 "chilean-sea-bass":"Chilean Sea Bass",
 "chopped-wedge-salad":"Chopped Wedge Salad",
 "colossal-carrot-cake":"Colossal Carrot Cake",
 "crab-cake":"Crab Cake",
 "creamed-corn":"Creamed Corn",
 "creamy-spicy-crab-dip":"Creamy Spicy Crab Dip",
 "dry-aged-new-york-strip":"Dry Aged New York Strip",
 "filet-lobster":"Filet & Lobster",
 "filet-mignon":"Filet Mignon",
 "gem-caesar":"Caesar / Gem Caesar",
 "goat-cheese-spread":"Goat Cheese Spread",
 "grilled-asparagus":"Grilled Asparagus",
 "house-salad":"House Salad",
 "jalapeno-potatoes-au-gratin":"Jalapeno Potatoes Au Gratin",
 "japanese-a5-wagyu":"Japanese A5 Wagyu",
 "k-d-s-tomahawk":"K.D.'s Tomahawk",
 "lobster-bisque":"Lobster Bisque",
 "lobster-mac-n-cheese":"Lobster Mac N' Cheese",
 "mo-s-cookie":"Mo's Cookie / Prime Cookie",
 "molten-lava-cake":"Molten Lava Cake",
 "ny-style-cheesecake":"NY Style Cheesecake",
 "primavera-pasta":"Primavera Pasta",
 "prime-meatballs":"Prime Meatballs",
 "roasted-pear-salad":"Roasted Pear Salad",
 "short-rib-pasta":"Short Rib Pasta",
 "shrimp-cocktail":"Shrimp Cocktail",
 "steak-47":"Steak 47",
 "the-mo-s-sundae":"The Mo's Sundae",
 "truffle-fries":"Truffle Fries",
 "white-cheddar-mashed-potatoes":"White Cheddar Mashed Potatoes",
}

# one photo standing in for a second item that is the same food
ALSO = {"Filet Mignon":["4 oz Filet Mignon"]}

out, total, missing = {}, 0, []
for slug, dish in DISHES.items():
    p = os.path.join(SRC, slug + ".jpg")
    if not os.path.exists(p):
        missing.append(slug); continue
    im = Image.open(p).convert("RGB")
    if im.size != (PX, PX):
        im = im.resize((PX, PX), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=Q, optimize=True, progressive=True)
    total += buf.tell()
    uri = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()
    out[dish] = uri
    for extra in ALSO.get(dish, []):
        out[extra] = uri

js = ("\n/* ============ DISH PHOTOS — generated by mkphotos.py. Do not hand-edit.\n"
      f"   {len(DISHES)} dishes, {PX}px square, embedded because the app is one file. ============ */\n"
      "const PHOTOS=" + json.dumps(out, ensure_ascii=False) + ";\n")
(ROOT / "build" / "5d-data-photos.js").write_text(js, encoding="utf-8")

print(f"PHOTOS: {len(DISHES)} dishes -> {len(out)} keys")
print(f"  {PX}px q{Q} · raw {total/1024:.0f}KB · file {len(js)/1024:.0f}KB")
if missing: print("  MISSING SOURCE:", missing)
