#!/usr/bin/env python3
"""deck-content.json (written by mkdeck.js) -> build/5e-data-deck.js

The PowerPoint and the in-app slideshow are the SAME deck. Edit mkdeck.js,
re-run it, re-run this, rebuild. Never hand-edit 5e-data-deck.js."""
import json, pathlib, html, sys

src = pathlib.Path("deck-content.json")
if not src.exists():
    sys.exit("deck-content.json missing — run `node mkdeck.js` first")
slides = json.loads(src.read_text(encoding="utf-8"))


def e(t):
    return html.escape(str(t or ""), quote=False)


def render(sl):
    out = []
    for b in sl["b"]:
        t, d = b["t"], b["d"]
        if t == "rows":
            out.append('<ol class="dkrows">' + "".join(
                f'<li><b>{e(h)}</b>{" " + e(body) if body else ""}</li>' for h, body in d) + "</ol>")
        elif t == "cards":
            out.append('<div class="dkcards">' + "".join(
                f'<div class="dkcard"><h4>{e(h)}</h4>'
                f'{f"<span>{e(sub)}</span>" if sub else ""}'
                f'{f"<p>{e(body)}</p>" if body else ""}</div>' for h, sub, body in d) + "</div>")
        elif t == "cols":
            for col in d:
                if col.get("head"):
                    out.append(f'<h5>{e(col["head"])}</h5>')
                out.append("<ul class=\"dklist\">" + "".join(f"<li>{e(x)}</li>" for x in col["items"]) + "</ul>")
        elif t == "note":
            out.append(f'<div class="dknote"><b>{e(d[0])}</b> {e(d[1])}</div>')
        elif t == "shout":
            out.append(f'<p class="dkshout">{e(d)}</p>')
        elif t == "quote":
            out.append(f'<p class="dkquote">{e(d[0])}</p>')
            if d[1]:
                out.append(f'<p class="dksub">{e(d[1])}</p>')
        elif t == "swap":
            out.append('<div class="dkswap">' + "".join(
                f'<div><s>{e(a)}</s><i>&#8594;</i><b>{e(bb)}</b></div>' for a, bb in d) + "</div>")
        elif t == "toc":
            out.append("__TOC__")
    return "".join(out)


js = []
for sl in slides:
    js.append({
        "k": sl["k"],
        "t": sl["t"],
        "s": sl["s"],
        "d": sl["d"],
        "n": sl.get("n"),
        "h": render(sl),
    })

body = ",\n ".join(json.dumps(x, ensure_ascii=False) for x in js)
out = ("\n/* ============ THE TRAINING SLIDESHOW — generated by mkdeck.js + mkslides.py.\n"
       "   Do not hand-edit. Same content as the PowerPoint, one slide at a time.\n"
       "   %d slides. ============ */\n"
       "const DECK=[\n %s\n];\n") % (len(js), body)

pathlib.Path("build/5e-data-deck.js").write_text(out, encoding="utf-8")
shots = sum(1 for x in js if x["k"] == "shot")
print("build/5e-data-deck.js — %d slides (%d placeholder, %d day dividers)"
      % (len(js), shots, sum(1 for x in js if x["k"] == "day")))
